// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Removed typed Database import to avoid schema mismatch during setup

const SUPABASE_URL = "https://uhswspoazydiofmwjytr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoc3dzcG9henlkaW9mbXdqeXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NDM2NjYsImV4cCI6MjA3MzExOTY2Nn0.MQhzWXP9ou59LxnLVs6j3QXnEr_5JA_xLwIpQmfjcVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});